In [ ]:
import pandas as pd
df = pd.read_csv("formated_data3.csv",encoding="ISO-8859-1")
df['event_date']=pd.to_datetime(df["event_date"],infer_datetime_format=True)

In [ ]:
#dropping empty and rows with unknown
df.dropna(
    axis=0,
    how='any',
    thresh=None,
    subset=None,
    inplace=True
)
df = df[df.landslide_trigger != 'unknown']
df = df[df.landslide_setting != 'unknown']
df.drop_duplicates()

event_date landslide_category landslide_trigger landslide_size  \
0    2015-05-17 00:00:00          landslide              rain         medium   
1    2016-10-01 00:00:00          landslide          downpour         medium   
2    2015-04-02 00:00:00          landslide   continuous_rain         medium   
3    2015-07-19 00:00:00          landslide          downpour          small   
4    2015-10-21 00:00:00          landslide              rain         medium   
...                  ...                ...               ...            ...   
1702 2015-03-05 09:00:00           mudslide              rain          small   
1703 2014-12-02 00:00:00        debris_flow              rain         medium   
1704 2016-10-24 23:00:00          rock_fall      construction         medium   
1705 2015-11-16 09:00:00          landslide          downpour         medium   
1706 2015-01-20 00:00:00          landslide          downpour         medium   

     landslide_setting  fatality_count  injury_count country_code  \
0                urban               0             0           MX   
1                bluff               0             0           GB   
2        natural_slope               0             0           IN   
3           above_road               0             0           US   
4           above_road               0             0           MX   
...                ...             ...           ...          ...   
1702        above_road               0             0           US   
1703       burned_area               0             0           US   
1704              mine               0             2           CA   
1705     natural_slope               0             0           MY   
1706              mine               2             3           PK   

     admin_division_name  admin_division_population  longitude  latitude  \
0        Baja California                       1173  -117.0898   32.5196   
1                England                       2565     0.8546   51.4216   
2                Kashmir                      14965    74.4725   34.1587   
3             California                      20292  -116.9029   33.0742   
4                Chiapas                      19092   -92.2523   15.3482   
...                  ...                        ...        ...       ...   
1702       West Virginia                       1344   -81.2565   37.7028   
1703          California                       3249  -118.9858   34.1946   
1704    British Columbia                       4038  -116.4362   51.4197   
1705        Kuala Lumpur                    1453975   101.7036    3.1497   
1706         Balochist?n                       7630    67.3799   30.6218   

      temp  humidity  wind  
0     16.4      74.0  13.6  
1     12.3      88.0  11.3  
2      5.2      92.0   4.3  
3     21.3      93.0  11.8  
4     18.2      92.0   3.6  
...    ...       ...   ...  
1702  -0.9      95.0  14.3  
1703  17.8      73.0   3.3  
1704   3.9      81.0   4.3  
1705  27.4      82.0   3.7  
1706   2.0      78.0   7.0  

[1683 rows x 15 columns]

In [ ]:
#splitting date time into columns
df['event_date_year'] = df['event_date'].dt.year
df['event_date_month'] = df['event_date'].dt.month
df['event_date_week'] = df['event_date'].dt.week
df['event_date_day'] = df['event_date'].dt.day
df['event_date_hour'] = df['event_date'].dt.hour
df['event_date_minute'] = df['event_date'].dt.minute
df['event_date_dayofweek'] = df['event_date'].dt.dayofweek
df = df.drop('event_date', axis=1)

<ipython-input-14-534d57747069>:4: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  df['event_date_week'] = df['event_date'].dt.week


In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

df['country_code']=le.fit_transform(df['country_code'])
df['landslide_category']=le.fit_transform(df['landslide_category'])
df['landslide_trigger']=le.fit_transform(df['landslide_trigger'])
df['landslide_setting']=le.fit_transform(df['landslide_setting'])
df['landslide_size']=le.fit_transform(df['landslide_size'])
df['admin_division_name']=le.fit_transform(df['admin_division_name'])

In [ ]:
X=df
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X=pd.DataFrame(scaler.fit_transform(X),index=X.index, columns=X.columns)
Y = df['landslide_trigger']
X=X.drop('landslide_trigger',axis=1)

In [ ]:
#X_backup=X
#X=X_backup
#X=X[['temp','longitude','landslide_category','wind','landslide_setting','admin_division_population','country_code','fatality_count','latitude','landslide_size']]
X=X[['temp','longitude','landslide_category','wind','landslide_setting','admin_division_population','country_code','latitude','fatality_count']]
#X=X[['temp','longitude','wind','admin_division_population','latitude']]
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [ ]:
import statistics
import random
from sklearn.metrics import accuracy_score
from sklearn .dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import sklearn.metrics as metrics


MostFrequentModel=DummyClassifier(strategy="most_frequent")
MostFrequentModel.fit(X_train,Y_train)
y_pred=MostFrequentModel.predict(X_train)
print("Accuracy score:",metrics.accuracy_score(Y_train, y_pred))
print("Precision Score : ",metrics.precision_score(Y_train,y_pred,pos_label='positive',average='weighted'))
print("Recall Score :" , metrics.recall_score(Y_train, y_pred, pos_label='positive',average='weighted') )
print("F1 Score :" , metrics.f1_score(Y_train, y_pred, pos_label='positive',average='weighted') )


y_pred=MostFrequentModel.predict(X_test)
print("Accuracy score:",metrics.accuracy_score(Y_test, y_pred))
print("Precision Score : ",metrics.precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print("Recall Score :" , metrics.recall_score(Y_test, y_pred, pos_label='positive',average='weighted') )
print("F1 Score :" , metrics.f1_score(Y_test, y_pred, pos_label='positive',average='weighted') )


Accuracy score: 0.3713862120088955
Precision Score :  0.13792771847031626
Recall Score : 0.3713862120088955
F1 Score : 0.20115080239616936
Accuracy score: 0.33136094674556216
Precision Score :  0.10980007702811527
Recall Score : 0.33136094674556216
F1 Score : 0.16494411571334652


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics

n_estimators=range(1,1300,100)
mean_f1=[]
std_f1=[]

for i in n_estimators:
  RFCModel=RandomForestClassifier(n_estimators=i)
  RFCModel.fit(X_train,Y_train)
  ypred=RFCModel.predict(X_test)
  f1_scores = cross_val_score(RFCModel, X, Y, cv=5, scoring='f1_macro', n_jobs=-1)
  mean_f1.append(np.array(f1_scores).mean())
  std_f1.append(np.array(f1_scores).std())

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/mod

In [ ]:
#plotting cross validation
fig=plt.figure()
fig.set_size_inches(15.5, 10.5)
ax=fig.add_subplot(111)
ax.errorbar(n_estimators,mean_f1,label='mean',yerr=std_f1)
ax.set_ylabel("F1 score")
ax.set_xlabel("n_estimators")
ax.legend(bbox_to_anchor=(1.05, 1),loc='upper left', borderaxespad=0.)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics

max_depth=range(1,50,5)
mean_f1=[]
std_f1=[]

for i in max_depth:
  RFCModel=RandomForestClassifier(n_estimators=1200,max_depth=i)
  RFCModel.fit(X_train,Y_train)
  ypred=RFCModel.predict(X_test)
  f1_scores = cross_val_score(RFCModel, X, Y, cv=5, scoring='f1_macro', n_jobs=-1)
  mean_f1.append(np.array(f1_scores).mean())
  std_f1.append(np.array(f1_scores).std())

In [ ]:
#plotting cross validation
fig=plt.figure()
fig.set_size_inches(15.5, 10.5)
ax=fig.add_subplot(111)
ax.errorbar(max_depth,mean_f1,label='mean',yerr=std_f1)
ax.set_ylabel("F1 score")
ax.set_xlabel("max_depth")
ax.legend(bbox_to_anchor=(1.05, 1),loc='upper left', borderaxespad=0.)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import sklearn.metrics as metrics

min_samples_split=range(2,6)
mean_f1=[]
std_f1=[]

for i in min_samples_split:
  RFCModel=RandomForestClassifier(n_estimators=1200,max_depth=20,min_samples_split=i)
  RFCModel.fit(X_train,Y_train)
  ypred=RFCModel.predict(X_test)
  f1_scores = cross_val_score(RFCModel, X, Y, cv=5, scoring='f1_macro', n_jobs=-1)
  mean_f1.append(np.array(f1_scores).mean())
  std_f1.append(np.array(f1_scores).std())

In [ ]:
#plotting cross validation
fig=plt.figure()
fig.set_size_inches(15.5, 10.5)
ax=fig.add_subplot(111)
ax.errorbar(min_samples_split,mean_f1,label='mean',yerr=std_f1)
ax.set_ylabel("F1 score")
ax.set_xlabel("min_samples_split")
ax.legend(bbox_to_anchor=(1.05, 1),loc='upper left', borderaxespad=0.)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
import sklearn.metrics as metrics

RFCModel=RandomForestClassifier(n_estimators=1200,max_depth=20,min_samples_split=5)
RFCModel.fit(X_train,Y_train)

In [ ]:
from sklearn.metrics import plot_confusion_matrix
y_pred=RFCModel.predict(X_train)
print("Accuracy score:",metrics.accuracy_score(Y_train, y_pred))
print("Precision Score : ",metrics.precision_score(Y_train,y_pred,pos_label='positive',average='weighted'))
print("Recall Score :" , metrics.recall_score(Y_train, y_pred, pos_label='positive',average='weighted') )
print("F1 Score :" , metrics.f1_score(Y_train, y_pred, pos_label='positive',average='weighted') )

print(metrics.confusion_matrix(Y_train,y_pred))


Accuracy score: 0.9873980726464048
Precision Score :  0.9874889682853678
Recall Score : 0.9873980726464048
F1 Score : 0.9872507573415754
[[ 27   0   0   2   0   0   0   0   0   0   0   0   0   0   0]
 [  0 209   0   3   0   0   0   0   0   0   0   1   0   1   0]
 [  0   0   5   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1   0 500   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0   0  32   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  24   0   0   0   0   0   3   0   0   0]
 [  0   0   0   0   0   0  12   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  35   0   0   0   0   0   0   0]
 [  0   1   0   0   0   0   0   0  30   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  11   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0   2   0   0   0   0]
 [  0   1   0   0   0   0   0   0   0   0   0 359   0   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0  34   0   0]
 [  0   0   0   0   0   0   0   0   0   0   

/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(


In [ ]:
y_pred=RFCModel.predict(X_test)
print("Accuracy score:",metrics.accuracy_score(Y_test, y_pred))
print("Precision Score : ",metrics.precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print("Recall Score :" , metrics.recall_score(Y_test, y_pred, pos_label='positive',average='weighted') )
print("F1 Score :" , metrics.f1_score(Y_test, y_pred, pos_label='positive',average='weighted') )

print(metrics.confusion_matrix(Y_test,y_pred))

Accuracy score: 0.4556213017751479
Precision Score :  0.44530736357659434
Recall Score : 0.4556213017751479
F1 Score : 0.4213060142407431
[[ 0  0  0  1  0  0  0  0  0  0  0  1  0]
 [ 0 20  0 28  0  0  0  0  0  0 15  0  2]
 [ 0  0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0 14  0 77  0  0  0  1  0  0 18  0  1]
 [ 0  2  0  6  3  0  0  0  0  0  1  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  4  0  0  0  2  0  0  1  0  0]
 [ 0  3  0  3  0  0  0  0  1  0  1  0  0]
 [ 0  0  0  5  0  0  0  0  0  0  1  0  0]
 [ 0  5  0 40  1  0  0  0  0  0 45  2  1]
 [ 0  1  0  6  0  0  0  0  0  0  8  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  0  5]]


/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1370: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 